[build]
  publish = "dist/"
  command = "npm run generate --quiet --modern"



[build.environment]
  NPM_FLAGS = "--no-optional"
  CI = "1"


# https://docs.netlify.com/configure-builds/file-based-configuration/#redirects

# old node redirect
[[redirects]]
  from = "/app/node"
  to = "/app/nodejs"
  status = 301

[[redirects]]
  from = "/kind/entertainment"
  to = "/kind/entertainment-and-media-apps/"
  status = 301

[[redirects]]
  from = "/kind/photo-tools"
  to = "/kind/photo-and-graphic-tools/"
  status = 301
